### ISSUE TITLE
How can I implement bsv to bitcore-node?

### ISSUE THREAD

**Issue by kycfeel** [moneybutton/bsv#162]
Hi there.

I'm trying to implement `bsv` support into my `bitcore-node`. But I'm getting this error below when I try to start it. Is there anyone who tried to implement bsv into the bitcore-node? I need help with this 😵.

Thank you.

```
Unhandled Rejection at: Error: More than one instance of bitcore-lib-cash found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
bitcore-node_1  |     at Object.bitcore.versionGuard (/usr/src/app/packages/bitcore-node/node_modules/bsv/index.js:12:11)
bitcore-node_1  |     at Object.<anonymous> (/usr/src/app/packages/bitcore-node/node_modules/bsv/index.js:15:9)
bitcore-node_1  |     at Module._compile (internal/modules/cjs/loader.js:701:30)
bitcore-node_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
bitcore-node_1  |     at Module.load (internal/modules/cjs/loader.js:600:32)
bitcore-node_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
bitcore-node_1  |     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
bitcore-node_1  |     at Module.require (internal/modules/cjs/loader.js:637:17)
bitcore-node_1  |     at require (internal/modules/cjs/helpers.js:22:18)
bitcore-node_1  |     at LibProvider.register (/usr/src/app/packages/bitcore-node/src/providers/libs/index.ts:10:31)
bitcore-node_1  |     at new BSVModule (/usr/src/app/packages/bitcore-node/src/modules/bitcoin-sv/index.ts:9:19)
bitcore-node_1  |     at ModuleManager.loadConfigured (/usr/src/app/packages/bitcore-node/src/modules/index.ts:49:34)
bitcore-node_1  |     at Object.exports.FullClusteredWorker (/usr/src/app/packages/bitcore-node/src/workers/all.ts:35:11)
bitcore-node_1  |     at Object.<anonymous> (/usr/src/app/packages/bitcore-node/src/server.ts:4:1)
bitcore-node_1  |     at Module._compile (internal/modules/cjs/loader.js:701:30)
bitcore-node_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
bitcore-node_1  | Shutting down 62
```

### Package.json

```
(...)
"bsv": "0.24.1",
"bsv-p2p": "git+https://github.com/deanmlittle/bsv-p2p.git",
(...)
```

### ./src/modules/bitcoin-sv/index.ts

```
import { BaseModule } from '..';
import { BSVStateProvider } from '../../providers/chain-state/bsv/bsv';
import { BitcoinP2PWorker } from '../bitcoin/p2p';
import { VerificationPeer } from '../bitcoin/VerificationPeer';

export default class BSVModule extends BaseModule {
  constructor(services) {
    super(services);
    services.Libs.register('BSV', 'bsv', 'bsv-p2p');
    services.P2P.register('BSV', BitcoinP2PWorker);
    services.CSP.registerService('BSV', new BSVStateProvider());
    services.Verification.register('BSV', VerificationPeer);
  }
}
```

### ./src/providers/chain-state/bsv/bsv.ts

```
import { CacheStorage } from '../../../models/cache';
import { GetEstimateSmartFeeParams } from '../../../types/namespaces/ChainStateProvider';
import { BTCStateProvider } from '../btc/btc';

export class BSVStateProvider extends BTCStateProvider {
  constructor(chain: string = 'BSV') {
    super(chain);
  }

  async getFee(params: GetEstimateSmartFeeParams) {
    const { chain, network } = params;
    const cacheKey = `getFee-${chain}-${network}`;
    return CacheStorage.getGlobalOrRefresh(
      cacheKey,
      async () => {
        return { feerate: await this.getRPC(chain, network).getEstimateFee() };
      },
      30 * CacheStorage.Times.Minute
    );
  }
}
```

### ./src/chain.ts

```
module.exports = {
  BTC: {
    lib: require('bitcore-lib'),
    p2p: require('bitcore-p2p')
  },
  BCH: {
    lib: require('bitcore-lib-cash'),
    p2p: require('bitcore-p2p-cash')
  },
  LTC: {
    lib: require('litecore-lib'),
    p2p: require('litecore-p2p')
  },
  BSV: {
    lib: require('bsv'),
    p2p: require('bsv-p2p')
    },
  DOGE: {
    lib: require('@csio.company/dogecore-lib'),
    p2p: require('@csio.company/dogecore-p2p')
    },
  DSH: {
    lib: require('@dashevo/dashcore-lib'),
    p2p: require('@dashevo/dashcore-p2p')
    }
};
```

**Comment by ryanxcharles** [comment]
we're not going to add support for bitcore in any way
